version: "3.9"
   
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 6969Cutlass
      MYSQL_DATABASE: realmethods02012001
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  platform:
    image: realmethods/knowops:latest
    ports:
      - "8080:8080"
    environment:
        DATABASE_URL: jdbc:mysql://db:3306/realmethods02012001?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        DATABASE_PASSWORD: 6969Cutlass
    depends_on:
      - db
    links:
      - db
